name: Clippy

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true

      - name: Find changed directories with Cargo.toml
        id: find_folders
        run: |
          # Get a list of changed Cargo.toml files
          CHANGED_FILES=$(git diff --name-only ${{ github.base_ref || 'HEAD^' }} -- '*.toml' | grep "Cargo.toml" || true)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed Cargo.toml files detected."
            echo "changed_folders=none" >> $GITHUB_ENV
          else
            CHANGED_FOLDERS=$(echo "$CHANGED_FILES" | xargs -n1 dirname | sort | uniq)
            echo "Changed folders: $CHANGED_FOLDERS"
            echo "changed_folders=$CHANGED_FOLDERS" >> $GITHUB_ENV
          fi

      - name: Run Clippy for each changed folder
        if: env.changed_folders != 'none'
        run: |
          for folder in $changed_folders; do
            echo "Running clippy in $folder..."
            cargo clippy --manifest-path $folder/Cargo.toml --quiet || exit 1
          done
