name: Clippy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: Find and run clippy
        run: |
          for dir in $(find . -name Cargo.toml -exec dirname {} \;); do
            cd $dir
            cargo fmt --all
            cargo clippy --all-targets --all-features -- -D warnings
            cd -
          done
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Auto-format code"
            git push
          fi


# name: Clippy

# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions-rs/toolchain@v1
#         with:
#           toolchain: stable
#           profile: minimal
#           components: clippy, rustfmt
#           override: true
#       - name: Run clippy
#         run: make lint
  
