name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true

      - name: Find changed directories with Cargo.toml or Rust files
        id: find_folders
        run: |
          # Get a list of changed Cargo.toml or .rs files
          CHANGED_FILES=$(git diff --name-only ${{ github.base_ref || 'HEAD^' }} -- '*.toml' '*.rs' || true)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed Cargo.toml or Rust files detected."
            echo "changed_folders=none" >> $GITHUB_ENV
          else
            # Normalize directories and store them in GITHUB_ENV
            CHANGED_FOLDERS=$(echo "$CHANGED_FILES" | xargs -n1 dirname | sort | uniq)
            echo "Changed folders: $CHANGED_FOLDERS"
            printf "%s\n" "$CHANGED_FOLDERS" > changed_folders.txt
            echo "changed_folders=$(cat changed_folders.txt | tr '\n' ' ')" >> $GITHUB_ENV
          fi

      - name: Run Tests for each changed folder
        if: env.changed_folders != 'none'
        run: |
          for folder in ${{ env.changed_folders }}; do
            echo "Running tests in $folder..."
            cargo test --manifest-path $folder/Cargo.toml || exit 1
          done
