name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true

      - name: Find changed directories with Cargo.toml
        id: find_folders
        run: |
          # Get a list of changed folders containing Cargo.toml
          CHANGED_FOLDERS=$(git diff --name-only ${{ github.base_ref || 'HEAD^' }} -- '*.toml' | grep "Cargo.toml" | xargs -n1 dirname)
          if [ -z "$CHANGED_FOLDERS" ]; then
            echo "No new or modified folders with Cargo.toml found."
            echo "changed_folders=none" >> $GITHUB_ENV
          else
            echo "Changed folders with Cargo.toml: $CHANGED_FOLDERS"
            echo "changed_folders=$CHANGED_FOLDERS" >> $GITHUB_ENV
          fi

      - name: Run Tests for each changed folder
        if: env.changed_folders != 'none'
        run: |
          for folder in $changed_folders; do
            echo "Running tests in $folder..."
            cargo test --manifest-path $folder/Cargo.toml || exit 1
          done
